// <auto-generated />
namespace Sadco.FamilyDoctor.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class appLocations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(appLocations));
        
        string IMigrationMetadata.Id
        {
            get { return "201804271059014_appLocations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
